name: CI

# Copyright (c) 2026 Paul Sinclair
# SPDX-License-Identifier: MIT
#

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    name: Build and Test (Linux)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make

      - name: Run tests
        run: ./test_litetest
